export const ALL_RESTAURANTS_REQUEST = 'ALL_RESTAURANTS_REQUEST'
export const ALL_RESTAURANTS_SUCCESS = 'ALL_RESTAURANTS_SUCCESS'
export const ALL_RESTAURANTS_FAIL = 'ALL_RESTAURANTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'